profiles/urls.py
from django.urls import path

from profiles.views import base, ajax

urlpatterns = [
    path('profile/', base.full_profile, name='profile'),
    path('profile/edit/', ajax.edit_profile, name='edit_profile'),
    path('profile/edit/address', ajax.edit_address, name='edit_address'),
    path('profile/<str:username>/', base.public_profile, name='public_profile'),
    path('search/school/', ajax.search_school, name='search_school'),
]

profiles/models.py
from django.conf import settings
from django.core.validators import FileExtensionValidator
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.db.models.signals import post_save
from django.dispatch import receiver

from PIL import Image

from profiles.validators import FileSizeValidator
from profiles import settings as profile_settings

ACCOUNT_TYPE = (
    ('PT', _('Primary School Teacher')),
    ('ST', _('Secondary School Teacher')),
    ('S', _('Student')),
    ('O', _('Enthusiast')),
)

GENDER = (
    ('M', _('Male')),
    ('F', _('Female')),
)

COUNTRY = (
    ('SK', _('Slovakia')),
    ('CZ', _('Czechia')),
    ('HU', _('Hungary')),
    ('PL', _('Poland')),
    ('XX', _('Other (insert into note)')),
)


class Address(models.Model):
    street = models.CharField(max_length=250, verbose_name=_("Street"))
    city = models.CharField(max_length=250, verbose_name=_("City"))
    postal_code = models.CharField(max_length=250, verbose_name=_("Postal code"))
    country = models.CharField(max_length=2, verbose_name=_("Country"), choices=COUNTRY, default='SK')
    note = models.CharField(max_length=250, verbose_name=_("Address note"), blank=True, null=True)

    def __str__(self):
        return f"{self.street}, {self.city} {self.postal_code} {self.country}"


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    phone_number = models.CharField(max_length=15, verbose_name=_("Phone"), blank=True, null=True)
    header_image = models.ImageField(verbose_name=_("Header image"), blank=True, null=True, upload_to='profile-headers',
                               validators=[
                                   FileExtensionValidator(["jpg", "jpeg", "png"]),
                                   FileSizeValidator(profile_settings.HEADER_MAX_FILE_SIZE),
                               ])
    address = models.ForeignKey(Address, blank=True, null=True, on_delete=models.RESTRICT)
    gender = models.CharField(max_length=1, verbose_name=_("Gender"), blank=True, null=True, choices=GENDER)
    account_type = models.CharField(max_length=2, verbose_name=_("Account type"), blank=True, null=True,
                                    choices=ACCOUNT_TYPE)
    avatar = models.ImageField(verbose_name=_("Avatar"), blank=True, null=True, upload_to='avatars',
                               validators=[
                                   FileExtensionValidator(["jpg", "jpeg", "png"]),
                                   FileSizeValidator(profile_settings.AVATAR_MAX_FILE_SIZE),
                               ])
    about = models.TextField(blank=True, null=True, verbose_name=_("About me"))
    metadata = models.JSONField(blank=True, null=True, verbose_name=_("Metadata"),
                                help_text=_("Metadata about user."))
    country = models.CharField(blank=True, null=True, max_length=2, choices=COUNTRY, default='SK',
                               verbose_name=_("Country"))
    metadata = models.JSONField(
        verbose_name=_("Metadata"), blank=True, null=True, help_text=_("Metadata about user.")
    )

    def __str__(self):
        return f"{self.user}"

    def save(self, *args, **kwargs):
        # TODO: process header image for public profile

        if self.avatar:
            super().save(*args, **kwargs)

            img = Image.open(self.avatar.path)

            if img.height > profile_settings.AVATAR_MAX_HEIGHT or img.width > profile_settings.AVATAR_MAX_WIDTH:
                output_size = (profile_settings.AVATAR_MAX_WIDTH, profile_settings.AVATAR_MAX_HEIGHT)
                img.thumbnail(output_size)
                img.save(self.avatar.path, quality=profile_settings.AVATAR_DEFAULT_QUALITY)
        else:
            super().save(*args, **kwargs)


@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def update_profile_signal(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()


class School(models.Model):
    name = models.CharField(max_length=250, verbose_name=_("Name"))
    description = models.TextField(blank=True, null=True, verbose_name=_("Description"),
                                   help_text=_('Brief description about school.'))
    address = models.ForeignKey(Address, on_delete=models.RESTRICT)
    members = models.ManyToManyField(settings.AUTH_USER_MODEL, through='Membership', blank=True)
    district = models.CharField(max_length=50, blank=True, null=True, verbose_name=_("District"))
    region = models.CharField(max_length=50, blank=True, null=True, verbose_name=_("Region"))
    founder = models.CharField(max_length=50, blank=True, null=True, verbose_name=_("Founder"))
    school_type = models.CharField(max_length=250, verbose_name=_("School type"), blank=True, null=True)
    gps_x = models.CharField(max_length=50, blank=True, null=True, verbose_name=_("GPS X"))
    gps_y = models.CharField(max_length=50, blank=True, null=True, verbose_name=_("GPS Y"))
    school_code = models.CharField(max_length=50, verbose_name=_("KODSKO"), blank=True, null=True)
    edu_id = models.CharField(max_length=50, verbose_name=_("EDUID"), blank=True, null=True)
    ineko_id = models.CharField(max_length=50, blank=True, null=True, verbose_name=_("INEKO ID"))
    underprivileged = models.IntegerField(blank=True, null=True, verbose_name=_("Unprivileged"))
    number_of_students = models.IntegerField(blank=True, null=True, verbose_name=_("Number of Students"))
    mail = models.CharField(blank=True, null=True, max_length=100, verbose_name=_("Email"))
    mail2 = models.CharField(blank=True, null=True, max_length=100, verbose_name=_("Email 3"))
    mail3 = models.CharField(blank=True, null=True, max_length=100, verbose_name=_("Email 3"))
    website = models.CharField(blank=True, null=True, max_length=100, verbose_name=_("Website"))

    timestamp_added = models.DateTimeField(verbose_name=_("Added"), auto_now_add=True)
    timestamp_modified = models.DateTimeField(verbose_name=_("Modified"), auto_now=True)

    def __str__(self):
        return f"{self.name} – {self.address} ({self.school_type})"


class Membership(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    school = models.ForeignKey(School, on_delete=models.RESTRICT)
    effective_from = models.DateField(blank=True, null=True, verbose_name=_("Effective from"))
    effective_to = models.DateField(blank=True, null=True, verbose_name=_("Effective to"))
    replaced_by = models.ForeignKey('Membership', blank=True, null=True, on_delete=models.RESTRICT, default=None,
                                    verbose_name=_("Replaced by"))
    proof = models.ImageField(verbose_name=_("Proof"), blank=True, null=True, upload_to='profile-school-proof',
                               validators=[
                                   FileExtensionValidator(["jpg", "jpeg", "png"]),
                                   FileSizeValidator(profile_settings.HEADER_MAX_FILE_SIZE),
                               ])
    verified = models.BooleanField(verbose_name=_("Verified"), default=False)

    def __str__(self):
        return f"{self.school}: {self.user}"

profiles/templates/profiles/full_profile.html
{% extends "base.html" %}
{% load i18n %}
{% load bootstrap5 %}

{% block breadcrumbs %}
  {% include "courses/includes/breadcrumbs.html" with breadcrumbs=breadcrumbs %}
{% endblock %}

{% block javascript %}
<script>
  document.body.addEventListener('htmx:configRequest', (event) => {
    event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
  })
</script>
{% endblock %}

{% block content %}
  <!-- Profile Modal -->
  <div class="modal fade" id="profileModal" tabindex="-1" aria-labelledby="profileModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="profileModalLabel">{% translate "Edit Profile" %}</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="{% translate "Close" %}"></button>
          </div>
          <div class="modal-body">
            {% bootstrap_form user_form %}
            {% bootstrap_form profile_form %}
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">{% translate "Close" %}</button>
            <button class="btn btn-primary btn-block" type="submit"  name="save_profile">
              <i class="fas fa-save"></i> {% translate "Save" %}
            </button>
          </div>
        </div>
      </form>
    </div>
  </div>

  <!-- Address Modal -->
  <div class="modal fade" id="addressModal" tabindex="-1" aria-labelledby="addressModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <form method="post">
        {% csrf_token %}
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="addressModalLabel">{% translate "Edit Address" %}</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="{% translate "Close" %}"></button>
          </div>
          <div class="modal-body">
            {% bootstrap_form address_form %}
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">{% translate "Close" %}</button>
            <button class="btn btn-primary btn-block" type="submit" name="save_address">
              <i class="fas fa-save"></i> {% translate "Save" %}
            </button>
          </div>
        </div>
      </form>
    </div>
  </div>

  <!-- School Modal -->
  <div class="modal fade" id="schoolModal" tabindex="-1" aria-labelledby="schoolModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
      <form method="post">
        {% csrf_token %}
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="schoolModalLabel">{% translate "Search School" %}</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="{% translate "Close" %}"></button>
          </div>
          <div class="modal-body">

            <span class="htmx-indicator">
              <i class="fas fa-spinner fa-spin"></i> {% translate "Searching..." %}
            </span>

            <input class="form-control" type="text" name="search" aria-describedby="searchHelp"
                   hx-post="{% url 'search_school' %}"
                   hx-trigger="keyup changed delay:500ms"
                   hx-target="#search-results"
                   hx-indicator=".htmx-indicator"
                   placeholder="{% translate "To search for your school begin with typing school code or address or name..." %}">
            <div id="searchHelp" class="form-text">
              {% translate "You can search your school by:" %}
              <ul>
                <li>{% translate "School code" %}</li>
                <li>{% translate "Street" %}</li>
                <li>{% translate "Name" %}</li>
              </ul>
            </div>

            <table class="table">
                <thead>
                <tr>
                  <th></th>
                  <th>{% translate "Name" %}</th>
                  <th>{% translate "Street" %}</th>
                  <th>{% translate "City" %}</th>
                  <th>{% translate "School code" %}</th>
                </tr>
                </thead>
                <tbody id="search-results">
                </tbody>
            </table>

          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">{% translate "Close" %}</button>
            <button class="btn btn-primary btn-block" type="submit" name="save_school">
              <i class="fas fa-save"></i> {% translate "Save" %}
            </button>
          </div>
        </div>
      </form>
    </div>
  </div>

  <div class="album py-5 {# bg-light #}">
    <div class="container">
      <div class="row g-3">

        <div class="col-6">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">{% translate "My Profile" %}</h5>
              <p class="card-text">
                {% translate "Username" %}: {{ request.user.username }}<br />
                {{ request.user.first_name }} {{ request.user.last_name }}<br />
                {{ request.user.email }}<br />
                {% if request.user.profile.phone_number %}{{ request.user.profile.phone_number }}<br />{% endif %}
                {% if request.user.profile.account_type %}{{ request.user.profile.get_account_type_display }}<br />{% endif %}
                {% if request.user.profile.gender %}{{ request.user.profile.get_gender_display|default_if_none:"" }}<br />{% endif %}
                {% if request.user.profile.about %}
                <p>{{ request.user.profile.about }}</p>
                {% endif %}
              </p>
              <!-- Button trigger modal -->
              <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#profileModal">
                {% translate "Edit Profile" %}
              </button>
            </div>
          </div>
        </div>

        <div class="col-6">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">{% translate "My Address" %}</h5>
              <p class="card-text">
                {{ request.user.profile.address.street }}<br />
                {{ request.user.profile.address.postal_code }} {{ request.user.profile.address.city }}<br />
                {{ request.user.profile.address.get_country_display }}<br />
              </p>
              <!-- Button trigger modal -->
              <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#addressModal">
                {% translate "Edit Address" %}
              </button>
            </div>
          </div>
        </div>

        <div class="col-6">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">{% translate "My School" %}</h5>
              <p class="card-text">
                {% for membership in request.user.membership_set.all %}
                  {% if not membership.replaced_by %}
                    {{ membership.school.name }}<br />
                    {{ membership.school.address.street }}<br />
                    {{ membership.school.address.postal_code }} {{ membership.school.address.city }}<br />
                    {{ membership.school.address.get_country_display }}<br />
                    {% if membership.school.website|first in 'http' %}
                      <a href="{{ membership.school.website }}" target="_blank" >{{ membership.school.website }}</a>
                    {% elif membership.school.website %}
                      <a href="http://{{ membership.school.website }}" target="_blank" >{{ membership.school.website }}</a>
                    {% endif %}<br />

                    {% translate "School code" %}: {{ membership.school.school_code }}<br />
                  {% endif %}
                {% endfor %}
              </p>
              <!-- Button trigger modal -->
              <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#schoolModal">
                {% translate "Edit School" %}
              </button>
            </div>
          </div>
        </div>

      </div>
    </div>
  </div>
{% endblock %}

profiles/templates/profiles/profile.html
{% extends "base.html" %}
{% load i18n %}
{% load bootstrap5 %}

{% block breadcrumbs %}
  {% include "courses/includes/breadcrumbs.html" with breadcrumbs=breadcrumbs %}
{% endblock %}

{% block javascript %}
<script>
  document.body.addEventListener('htmx:configRequest', (event) => {
    event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
  })
</script>
{% endblock %}

{% block content %}
  <!-- Profile Modal -->
  <div class="modal fade" id="profileModal" tabindex="-1" aria-labelledby="profileModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <form method="post">
        {% csrf_token %}
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="profileModalLabel">{% translate "Edit Profile" %}</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="{% translate "Close" %}"></button>
          </div>
          <div class="modal-body">
            {% bootstrap_form user_form %}
            {% bootstrap_form profile_form %}
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">{% translate "Close" %}</button>
            <button class="btn btn-primary btn-block" type="submit"  name="save_profile">
              <i class="fas fa-save"></i> {% translate "Save" %}
            </button>
          </div>
        </div>
      </form>
    </div>
  </div>

  <!-- Address Modal -->
  <div class="modal fade" id="addressModal" tabindex="-1" aria-labelledby="addressModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <form method="post">
        {% csrf_token %}
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="addressModalLabel">{% translate "Edit Address" %}</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="{% translate "Close" %}"></button>
          </div>
          <div class="modal-body">
            {% bootstrap_form address_form %}
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">{% translate "Close" %}</button>
            <button class="btn btn-primary btn-block" type="submit" name="save_address">
              <i class="fas fa-save"></i> {% translate "Save" %}
            </button>
          </div>
        </div>
      </form>
    </div>
  </div>

  <!-- School Modal -->
  <div class="modal fade" id="schoolModal" tabindex="-1" aria-labelledby="schoolModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
      <form method="post">
        {% csrf_token %}
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="schoolModalLabel">{% translate "Search School" %}</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="{% translate "Close" %}"></button>
          </div>
          <div class="modal-body">

            <span class="htmx-indicator">
              <i class="fas fa-spinner fa-spin"></i> {% translate "Searching..." %}
            </span>

            <input class="form-control" type="text" name="search" aria-describedby="searchHelp"
                   hx-post="{% url 'search_school' %}"
                   hx-trigger="keyup changed delay:500ms"
                   hx-target="#search-results"
                   hx-indicator=".htmx-indicator"
                   placeholder="{% translate "To search for your school begin with typing school code or address or name..." %}">
            <div id="searchHelp" class="form-text">
              {% translate "You can search your school by:" %}
              <ul>
                <li>{% translate "School code" %}</li>
                <li>{% translate "Street" %}</li>
                <li>{% translate "Name" %}</li>
              </ul>
            </div>

            <table class="table">
                <thead>
                <tr>
                  <th></th>
                  <th>{% translate "Name" %}</th>
                  <th>{% translate "Street" %}</th>
                  <th>{% translate "City" %}</th>
                  <th>{% translate "School code" %}</th>
                </tr>
                </thead>
                <tbody id="search-results">
                </tbody>
            </table>

          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">{% translate "Close" %}</button>
            <button class="btn btn-primary btn-block" type="submit" name="save_school">
              <i class="fas fa-save"></i> {% translate "Save" %}
            </button>
          </div>
        </div>
      </form>
    </div>
  </div>

  <div class="album py-5 {# bg-light #}">
    <div class="container">
      <div class="row g-3">

        <div class="col-6">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">{% translate "My Profile" %}</h5>
              <p class="card-text">
                {% translate "Username" %}: {{ request.user.username }}<br />
                {{ request.user.first_name }} {{ request.user.last_name }}<br />
                {{ request.user.email }}<br />
                {% if request.user.profile.phone_number %}{{ request.user.profile.phone_number }}<br />{% endif %}
                {% if request.user.profile.account_type %}{{ request.user.profile.get_account_type_display }}<br />{% endif %}
                {% if request.user.profile.gender %}{{ request.user.profile.get_gender_display|default_if_none:"" }}<br />{% endif %}
                {% if request.user.profile.about %}
                <p>{{ request.user.profile.about }}</p>
                {% endif %}
              </p>
              <!-- Button trigger modal -->
              <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#profileModal">
                {% translate "Edit Profile" %}
              </button>
            </div>
          </div>
        </div>

        <div class="col-6">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">{% translate "My Address" %}</h5>
              <p class="card-text">
                {{ request.user.profile.address.street }}<br />
                {{ request.user.profile.address.postal_code }} {{ request.user.profile.address.city }}<br />
                {{ request.user.profile.address.get_country_display }}<br />
              </p>
              <!-- Button trigger modal -->
              <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#addressModal">
                {% translate "Edit Address" %}
              </button>
            </div>
          </div>
        </div>

        <div class="col-6">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">{% translate "My School" %}</h5>
              <p class="card-text">
                {% for membership in request.user.membership_set.all %}
                  {% if not membership.replaced_by %}
                    {{ membership.school.name }}<br />
                    {{ membership.school.address.street }}<br />
                    {{ membership.school.address.postal_code }} {{ membership.school.address.city }}<br />
                    {{ membership.school.address.get_country_display }}<br />
                    {% if membership.school.website|first in 'http' %}
                      <a href="{{ membership.school.website }}" target="_blank" >{{ membership.school.website }}</a>
                    {% elif membership.school.website %}
                      <a href="http://{{ membership.school.website }}" target="_blank" >{{ membership.school.website }}</a>
                    {% endif %}<br />

                    {% translate "School code" %}: {{ membership.school.school_code }}<br />
                  {% endif %}
                {% endfor %}
              </p>
              <!-- Button trigger modal -->
              <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#schoolModal">
                {% translate "Edit School" %}
              </button>
            </div>
          </div>
        </div>

      </div>
    </div>
  </div>
{% endblock %}